# Supported: GCC, CLANG, ICX
TOOLCHAIN ?= CLANG
# Supported: dp (double), sp (single)
PRECISION ?= dp
ENABLE_OPENMP ?= false
ENABLE_LIKWID ?= false

#Feature options
OPTIONS +=  -DARRAY_ALIGNMENT=64
#OPTIONS +=  -DVERIFICATION
#OPTIONS +=  -DVERBOSE_AFFINITY
#OPTIONS +=  -DVERBOSE_DATASIZE
#OPTIONS +=  -DVERBOSE_TIMER
